name: Update Stock Data Daily

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  update-stock-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11.5'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Fetch stock data
        run: |
          python manage.py fetch_main
