# Generated by Django 5.1.2 on 2024-10-29 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CSVData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isin', models.CharField(blank=True, max_length=40, null=True)),
                ('scheme_code', models.CharField(blank=True, max_length=50, null=True)),
                ('scheme_id', models.CharField(blank=True, max_length=50, null=True)),
                ('scheme_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheme_id', models.CharField(blank=True, max_length=25, null=True)),
                ('one_month_return', models.FloatField(blank=True, null=True)),
                ('six_month_return', models.FloatField(blank=True, null=True)),
                ('one_year_return', models.FloatField(blank=True, null=True)),
                ('three_year_return', models.FloatField(blank=True, null=True)),
                ('five_year_return', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sec_id', models.CharField(blank=True, max_length=255, null=True)),
                ('isin', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('investment_name', models.CharField(blank=True, max_length=255, null=True)),
                ('inceptionDate', models.DateField(blank=True, null=True)),
                ('prospectus_benchmark_name', models.CharField(blank=True, max_length=255, null=True)),
                ('expense_ratio', models.DecimalField(blank=True, decimal_places=5, max_digits=20, null=True)),
                ('last_turnover_ratio', models.DecimalField(blank=True, decimal_places=5, max_digits=20, null=True)),
                ('equity_style_box', models.CharField(blank=True, max_length=255, null=True)),
                ('expense', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('morningstar_rating', models.IntegerField(blank=True, null=True)),
                ('total_asset', models.DecimalField(blank=True, decimal_places=5, max_digits=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('master_portfolio_id', models.CharField(max_length=255, unique=True)),
                ('sec_id', models.CharField(blank=True, max_length=255, null=True)),
                ('base_currency_id', models.CharField(blank=True, max_length=10, null=True)),
                ('domicile_country_id', models.CharField(blank=True, max_length=10, null=True)),
                ('number_of_holding', models.IntegerField(blank=True, null=True)),
                ('number_of_equity_holding', models.IntegerField(blank=True, null=True)),
                ('portfolio_date', models.DateField(blank=True, null=True)),
                ('top_holding_weighting', models.FloatField(blank=True, null=True)),
                ('last_turnover', models.FloatField(blank=True, null=True)),
                ('last_turnover_date', models.DateField(blank=True, null=True)),
                ('average_turnover_ratio', models.FloatField(blank=True, null=True)),
                ('women_directors_percentage', models.FloatField(blank=True, null=True)),
                ('women_executives_percentage', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RiskVolatility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fund_id', models.CharField(max_length=100, null=True)),
                ('fund_name', models.CharField(blank=True, max_length=255, null=True)),
                ('category_name', models.CharField(blank=True, max_length=255, null=True)),
                ('index_name', models.CharField(blank=True, max_length=255, null=True)),
                ('calculation_benchmark', models.CharField(blank=True, max_length=255, null=True)),
                ('fund_alpha_1y', models.FloatField(blank=True, null=True)),
                ('fund_beta_1y', models.FloatField(blank=True, null=True)),
                ('fund_r_squared_1y', models.FloatField(blank=True, null=True)),
                ('fund_std_dev_1y', models.FloatField(blank=True, null=True)),
                ('fund_sharpe_1y', models.FloatField(blank=True, null=True)),
                ('fund_alpha_3y', models.FloatField(blank=True, null=True)),
                ('fund_beta_3y', models.FloatField(blank=True, null=True)),
                ('fund_r_squared_3y', models.FloatField(blank=True, null=True)),
                ('fund_std_dev_3y', models.FloatField(blank=True, null=True)),
                ('fund_sharpe_3y', models.FloatField(blank=True, null=True)),
                ('fund_alpha_5y', models.FloatField(blank=True, null=True)),
                ('fund_beta_5y', models.FloatField(blank=True, null=True)),
                ('fund_r_squared_5y', models.FloatField(blank=True, null=True)),
                ('fund_std_dev_5y', models.FloatField(blank=True, null=True)),
                ('fund_sharpe_5y', models.FloatField(blank=True, null=True)),
                ('category_alpha_1y', models.FloatField(blank=True, null=True)),
                ('category_beta_1y', models.FloatField(blank=True, null=True)),
                ('category_r_squared_1y', models.FloatField(blank=True, null=True)),
                ('category_std_dev_1y', models.FloatField(blank=True, null=True)),
                ('category_sharpe_1y', models.FloatField(blank=True, null=True)),
                ('category_alpha_3y', models.FloatField(blank=True, null=True)),
                ('category_beta_3y', models.FloatField(blank=True, null=True)),
                ('category_r_squared_3y', models.FloatField(blank=True, null=True)),
                ('category_std_dev_3y', models.FloatField(blank=True, null=True)),
                ('category_sharpe_3y', models.FloatField(blank=True, null=True)),
                ('category_alpha_5y', models.FloatField(blank=True, null=True)),
                ('category_beta_5y', models.FloatField(blank=True, null=True)),
                ('category_r_squared_5y', models.FloatField(blank=True, null=True)),
                ('category_std_dev_5y', models.FloatField(blank=True, null=True)),
                ('category_sharpe_5y', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Holding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('security_name', models.CharField(blank=True, max_length=255, null=True)),
                ('sec_id', models.CharField(blank=True, max_length=255, null=True)),
                ('weighting', models.FloatField(blank=True, null=True)),
                ('number_of_share', models.IntegerField(blank=True, null=True)),
                ('market_value', models.FloatField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('ticker', models.CharField(blank=True, max_length=10, null=True)),
                ('sector', models.CharField(blank=True, max_length=100, null=True)),
                ('total_return_1_year', models.FloatField(blank=True, null=True)),
                ('forward_pe_ratio', models.FloatField(blank=True, null=True)),
                ('stock_rating', models.IntegerField(blank=True, null=True)),
                ('assessment', models.CharField(blank=True, max_length=255, null=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to='mfapp.portfolio')),
            ],
        ),
    ]
