# Generated by Django 5.1.2 on 2024-10-30 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mfapp', '0002_remove_portfolio_women_directors_percentage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockDataRefresh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_refresh_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
