# Generated by Django 5.1.2 on 2024-10-30 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mfapp', '0003_stockdatarefresh'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
