# Generated by Django 5.1.2 on 2024-10-29 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mfapp', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fund',
            name='load',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
