# Generated by Django 5.1.2 on 2024-10-29 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mfapp', '0004_alter_fund_load'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amc',
            name='advisor_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
