# Generated by Django 5.1.2 on 2024-10-29 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mfapp', '0005_alter_amc_advisor_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amc',
            name='advisor_display_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
