# Generated by Django 5.1.2 on 2024-10-29 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mfapp', '0006_alter_amc_advisor_display_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amc',
            name='advisor_display_name',
        ),
        migrations.RemoveField(
            model_name='amc',
            name='region_id',
        ),
        migrations.RemoveField(
            model_name='amc',
            name='sub_advisor_id',
        ),
        migrations.RemoveField(
            model_name='amc',
            name='sub_advisor_name',
        ),
        migrations.RemoveField(
            model_name='fund',
            name='load',
        ),
        migrations.AlterField(
            model_name='amc',
            name='advisor_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='amc',
            name='advisor_type',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fund',
            name='amc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funds', to='mfapp.amc'),
        ),
    ]
