# Generated by Django 5.1.2 on 2024-10-29 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mfapp', '0007_remove_amc_advisor_display_name_remove_amc_region_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fund',
            name='amc',
        ),
    ]
