# Generated by Django 5.1.2 on 2024-10-29 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mfapp', '0008_remove_fund_amc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dt',
            name='isin',
        ),
        migrations.RemoveField(
            model_name='dt',
            name='scheme_code',
        ),
        migrations.RemoveField(
            model_name='dt',
            name='scheme_name',
        ),
    ]
