# Generated by Django 5.1.2 on 2024-10-29 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mfapp', '0009_remove_dt_isin_remove_dt_scheme_code_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dt',
        ),
    ]
