# Generated by Django 5.1.2 on 2024-10-29 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mfapp', '0010_delete_dt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheme_id', models.CharField(blank=True, max_length=25, null=True)),
                ('one_month_return', models.FloatField(blank=True, null=True)),
                ('six_month_return', models.FloatField(blank=True, null=True)),
                ('one_year_return', models.FloatField(blank=True, null=True)),
                ('three_year_return', models.FloatField(blank=True, null=True)),
                ('five_year_return', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
