# Generated by Django 5.1.2 on 2024-10-29 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mfapp', '0011_dt'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AMC',
        ),
        migrations.DeleteModel(
            name='Dt',
        ),
        migrations.DeleteModel(
            name='Fund',
        ),
        migrations.RemoveField(
            model_name='holding',
            name='portfolio',
        ),
        migrations.DeleteModel(
            name='RiskVolatility',
        ),
        migrations.DeleteModel(
            name='Holding',
        ),
        migrations.DeleteModel(
            name='Portfolio',
        ),
    ]
