name: Update Stock Data Every 5 Hours

on:
  schedule:
    - cron: '0 */2 * * *'

jobs:
  update-stock-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11.5'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Fetch stock data
        run: |
          python manage.py fetch_main

      - name: Update stock holdings
        run: |
          python manage.py holding 

      - name: Update stock info
        run: |
          python manage.py risk
          
      - name: Update stock info
        run: |
          python manage.py perfor
