name: Scheduled

on:
  schedule:
    - cron: '0 0 * * *'  # This runs every day at midnight UTC
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  update-stock-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11.5'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Fetch stock data
        run: |
          python manage.py fetch_main

      - name: Update stock holdings
        run: |
          python manage.py holding 

      - name: Update stock info
        run: |
          python manage.py risk
          
      - name: Update stock performance
        run: |
          python manage.py perfor  # Ensure this command is correct
